services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - company-service

  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  company-service:
    build: ./services/company-service
    ports:
      - '5001:5001'
    env_file: .env
    environment:
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo

volumes:
  mongo-data:
